### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by qsm-mz-hn** [NotIvny/ark-plugin#1]
![image](https://github.com/NotIvny/yunzai-characterRank-js/assets/108866283/4c8aba9f-225a-446d-8477-837d0d643b20)
![image](https://github.com/NotIvny/yunzai-characterRank-js/assets/108866283/10b0f76a-1f49-4c82-a156-7caac6c0e06e)
这段代码到底放在那里

**Comment by NotIvny** [comment]
fixed
240-241行中间加上
let characterID = Gscfg.roleNameToID(char.name,true) || Gscfg.roleNameToID(char.name,false)
