### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by touchscale** [NotIvny/ark-plugin#12]
![image](https://github.com/user-attachments/assets/893eb9cb-30ff-47fc-bbbd-752b096cf3e7)

**Comment by NotIvny** [comment]
可以打印一下这几个数据吗，以便定位错误原因
![image](https://github.com/user-attachments/assets/714b749c-911b-4e08-97f5-40782d14e947)

**Comment by touchscale** [comment]
> 可以打印一下这几个数据吗，以便定位错误原因
> ![image](https://github.com/user-attachments/assets/714b749c-911b-4e08-97f5-40782d14e947)
> 

command.2024-09-06.log
https://www.alipan.com/s/eoWurSnSdJK
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
已打印

**Comment by NotIvny** [comment]
f200649
已修复，前两名的本地伤害计算数据为空所致
![0b218c815ee12b130a0a40f8c4ee0f2d](https://github.com/user-attachments/assets/877b9c9e-78ad-4133-9e92-478d0b0dd241)

![dc3fa5329f8b42bfc179c643e1873b7c](https://github.com/user-attachments/assets/d3f8daac-009a-4399-b51b-4c110d4bfeaa)

**Comment by touchscale** [comment]
> f200649
> 已修复，前两名的本地伤害计算数据为空所致
> ![0b218c815ee12b130a0a40f8c4ee0f2d](https://github.com/user-attachments/assets/877b9c9e-78ad-4133-9e92-478d0b0dd241)
> 
> ![dc3fa5329f8b42bfc179c643e1873b7c](https://github.com/user-attachments/assets/d3f8daac-009a-4399-b51b-4c110d4bfeaa)
> 

![Screenshot_2024-09-07-17-23-10-705_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/b468b278-468e-4060-84e5-5431d67c77ac)

已经可以正常使用
