### ISSUE TITLE
ProfileDetail.js文件中Config is not defined

### ISSUE THREAD

**Issue by Chengzivzx** [NotIvny/ark-plugin#5]
![image](https://github.com/NotIvny/ark-plugin/assets/110247910/96290cb5-4f50-419e-a299-2911b199ea64)
![image](https://github.com/NotIvny/ark-plugin/assets/110247910/ec5499ec-d322-4e89-b24f-e63f263291a3)

GPT回答：
这个报错显示在文件 ProfileDetail.js 的第 244 行，指向 Config is not defined，这意味着在该文件中尝试访问一个名为 Config 的变量或对象，但它没有被定义。可能需要检查代码中是否正确导入或声明了 Config。

你需要确保在 ProfileDetail.js 文件中正确导入或声明了 Config。检查是否有任何地方引用了 Config，但没有定义它。如果 Config 是来自外部库或模块，确保正确导入了该库或模块。最后，确保 Config 变量或对象在被引用之前已经被正确定义。

**Comment by NotIvny** [comment]
已修复
