### ISSUE TITLE
查询角色面板报错

### ISSUE THREAD

**Issue by zaliangjun** [NotIvny/ark-plugin#6]
安卓喵崽
![c9c4afdb92974acda9038bcc4217ecbe](https://github.com/NotIvny/ark-plugin/assets/116992097/fbf1c5c1-8245-4e78-9a5e-d1006c9851ec)

**Comment by zaliangjun** [comment]
![Uploading c9c4afdb92974acda9038bcc4217ecbe.jpg…]()

**Comment by NotIvny** [comment]
删掉config.yaml重新生成，目前只是初步做了下配置文件功能

**Comment by zaliangjun** [comment]
谢谢，删掉后不会自动生成，我手动复制过去就正常了。
