### ISSUE TITLE
TRSS环境下#ark替换文件miao-rank报错 请问如何解决

### ISSUE THREAD

**Issue by YuapXc** [NotIvny/ark-plugin#8]
TRSS环境下#ark替换文件miao-rank报错 请问如何解决，报错如图：
![f903c1a8-295b-44fc-a147-f23c456abe35](https://github.com/user-attachments/assets/432db18f-e375-4dd9-8af6-9e5b9e76f4be)

**Comment by YuapXc** [comment]
看了readme似乎是“src path下的所有文件名”没有自动获取（？）

**Comment by NotIvny** [comment]
已修复，更新插件即可

**Comment by YuapXc** [comment]
谢谢大佬，已经可用啦（🫰
